version: '3'

networks:
  ideamall:

services:
  pwa:
    image: ideamall/pwa
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - 3000:3000
    networks:
      - ideamall
  caddy:
    depends_on:
      - pwa
    image: caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - ideamall
    command: caddy reverse-proxy --from your.domain.com --to pwa:3000
